username = "foo"

[jellyfin]
base_url = "http://localhost:8096"
api_key = "api-key-foo"

[radarr]
base_url = "http://localhost:7878"
api_key = "api-key-foo"
tags_to_keep = ["keep"]
retention_period = "2d"
unmonitor = false

[sonarr]
base_url = "http://localhost:7878"
api_key = "api-key-foo"
tags_to_keep = ["keep"]
retention_period = "1w"

[download_clients.qbittorrent]
base_url = "http://localhost:8080"
username = "admin"
password = "adminadmin"

[download_clients.deluge]
base_url = "http://localhost:8112"
password = "qwerty"
